spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc7th_db?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: umc7th
    password: umc7th123!
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: none